from das_utils.ais import extract_time_window, filter_near_positions
from das_utils.annotate import (
    annotate_file,
    benchmark_detections,
    build_annotations,
    labels_for_range,
    load_annotations,
    nearest_ship_distance_m,
    save_annotations,
)
from das_utils.augment import (
    add_noise,
    channel_dropout,
    crop,
    decimate,
    detrend,
    normalize,
    smooth_spatial,
    smooth_temporal,
    taper,
    time_mask,
    time_shift,
)
from das_utils.channels import (
    correlation_matrix,
    low_correlation_intervals,
    measure_correlation,
    neighbor_correlation,
    pair_correlation,
    sliding_neighbor_correlation,
)
from das_utils.context import (
    TargetSelector,
    context_window,
    greedy_decorrelated,
)
from das_utils.correlate import (
    closest_approach_offset,
    estimate_translation_offset,
    margin_sensitivity,
    to_epoch_seconds,
)
from das_utils.detect import (
    channel_baseline,
    cluster_detections,
    common_mode_suppression,
    detect_file,
    detect_stream,
    spatial_corroboration,
    sta_lta_ratio,
    sta_lta_stream,
    step_channels,
)
from das_utils.energy import bandpass_energy_image
from das_utils.evaluate import (
    compute_metrics,
    evaluate_at_ranges,
    ground_truth_crossings,
    match_detections,
)
from das_utils.geo import (
    apply_translation,
    build_nearest_tree,
    local_xy,
    nearest_index,
    offset_m,
    positions_to_geojson_linestring,
)
from das_utils.image import build_image
from das_utils.io import index_das_files, load_channel_positions, positions_arrays
from das_utils.psd import band_powers, channel_psd, dominant_frequency
from das_utils.quality import (
    channel_quality,
    measure_noise,
    persistence_score,
    select_persistent_channels,
)
from das_utils.radon import linear_radon_stack, radon_detect_stream, radon_score
from das_utils.spectral import (
    bandpass,
    bandstop,
    channel_shuffle,
    frequency_jitter,
    frequency_shift,
    gain_randomization,
    highpass,
    lowpass,
    mixup,
    notch,
    phase_shift,
    random_augment,
    spectral_mask,
    spectral_warp,
    time_warp,
)
from das_utils.stats import channel_stats, temporal_profile
from das_utils.wavelet import (
    morlet_cwt_power,
    morlet_cwt_power_series,
    morlet_scale_for_freq,
    wavelet_image,
)

__all__ = [
    "add_noise",
    "annotate_file",
    "apply_translation",
    "band_powers",
    "bandpass",
    "bandpass_energy_image",
    "bandstop",
    "benchmark_detections",
    "build_annotations",
    "build_image",
    "build_nearest_tree",
    "channel_baseline",
    "channel_dropout",
    "channel_quality",
    "channel_shuffle",
    "channel_stats",
    "closest_approach_offset",
    "cluster_detections",
    "common_mode_suppression",
    "compute_metrics",
    "context_window",
    "correlation_matrix",
    "crop",
    "decimate",
    "detect_file",
    "detect_stream",
    "detrend",
    "dominant_frequency",
    "channel_psd",
    "estimate_translation_offset",
    "evaluate_at_ranges",
    "extract_time_window",
    "filter_near_positions",
    "frequency_jitter",
    "frequency_shift",
    "gain_randomization",
    "greedy_decorrelated",
    "ground_truth_crossings",
    "highpass",
    "index_das_files",
    "labels_for_range",
    "linear_radon_stack",
    "load_annotations",
    "load_channel_positions",
    "local_xy",
    "low_correlation_intervals",
    "lowpass",
    "margin_sensitivity",
    "match_detections",
    "measure_correlation",
    "measure_noise",
    "mixup",
    "morlet_cwt_power",
    "morlet_cwt_power_series",
    "morlet_scale_for_freq",
    "nearest_index",
    "nearest_ship_distance_m",
    "neighbor_correlation",
    "normalize",
    "notch",
    "offset_m",
    "pair_correlation",
    "persistence_score",
    "phase_shift",
    "positions_arrays",
    "positions_to_geojson_linestring",
    "radon_detect_stream",
    "radon_score",
    "random_augment",
    "save_annotations",
    "select_persistent_channels",
    "sliding_neighbor_correlation",
    "smooth_spatial",
    "smooth_temporal",
    "spatial_corroboration",
    "spectral_mask",
    "spectral_warp",
    "sta_lta_ratio",
    "sta_lta_stream",
    "step_channels",
    "TargetSelector",
    "taper",
    "temporal_profile",
    "time_mask",
    "time_shift",
    "time_warp",
    "to_epoch_seconds",
    "wavelet_image",
]


def main() -> None:
    print("das-utils: import the package for its functions - see AGENTS.md for the recipes.")
